### ISSUE TITLE
Use Astropy CI helpers

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/solarbextrapolation#10]
Remove Obvious CI submodule and just clone the [astropy CI helpers](https://github.com/astropy/ci-helpers) repo at each build.

Any objections/potential problems with this @Alex-Ian-Hamilton,@Cadair? Looks like the Travis build has been failing for a while because of some problem with the Obvious CI step, maybe caused by an upstream change.

**Comment by Cadair** [comment]
Sure, would be great, this CI setup predates the glory of Ci Helpers.
